####
# docker run -it sapan2211/odl-karaf-boron:base /bin/bash
# ./distribution-karaf-0.5.0-Boron/bin/karaf
# feature:install  odl-restconf-all odl-ovsdb-openstack  odl-dlux-all odl-l2switch-al
# ctrl+d and exit
# sudo docker commit <container-id> sapan2211/odl-karaf-boron:4
# sudo docker push sapan2211/odl-karaf-boron:4
###
FROM sapan2211/odl-karaf-boron:4
CMD ["./distribution-karaf-0.5.0-Boron/bin/karaf"]
